name: Groups
on:
  workflow_dispatch:

jobs:
  job_1:
    name: Test groups
    runs-on: ubuntu-latest
    steps:
      - id: my-key
        env:
            DEBUG_ENABLED: ${{ secrets.ACTIONS_STEP_DEBUG }}
        if: "${{ env.DEBUG_ENABLED != '' }}"
        run: echo "DEFINED"
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
      - run: ruby .github/workflows/groups.rb
