name: Features
on:
  workflow_dispatch:
    inputs:
      kubernetes_namespaces_basename:
        description: 'kubernetes_namespaces_basename'
        type: string
        required: false
        default: 'namespace'
  issue_comment:
    types: [ created ]

jobs:
  job_1:
    name: I do that
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          # Set ENV variables
          echo "KUBERNETES_NAMESPACE_BASE=${{ inputs.kubernetes_namespaces_basename }}" >> $GITHUB_ENV

      - shell: bash
        run: |
          # Validate Kubernetes namespace name
          regex="[a-z0-9]([-a-z0-9]*[a-z0-9])?"
          if ! [[ ${{ env.KUBERNETES_NAMESPACE_BASE }} =~ ^$regex$ ]]; then
            echo "Invalid Kubernetes namespace ${{ env.KUBERNETES_NAMESPACE_BASE }}! Should match the following regex: <pre>$regex</pre>" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
