name: Features
on:
  workflow_dispatch:
    inputs:
      release_candidate:
        description: 'Whether the build is part of an RC'
        type: string
        required: false
        default: 'false'
  issue_comment:
    types: [ created ]

jobs:
  job_1:
    name: I do that
    runs-on: ubuntu-latest
    steps:
      - name: I do it, yes
        run: |
          echo ${{ github.event.inputs.release_candidate == 'true' && 'ci.release-candidate=true' || 'alternative' }}
